# Generated by Django 3.2 on 2022-03-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top_slider',
            options={'ordering': ['-id'], 'verbose_name': 'Top Slider', 'verbose_name_plural': 'Top Sliders'},
        ),
        migrations.AlterField(
            model_name='top_slider',
            name='image',
            field=models.ImageField(upload_to='TopSliderImage'),
        ),
    ]
