# Generated by Django 3.2 on 2022-03-25 17:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeapp', '0002_auto_20220325_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='ServiceImage')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Our_Service',
                'verbose_name_plural': 'Our_Services',
                'ordering': ['-id'],
            },
        ),
    ]
