# Generated by Django 3.2 on 2022-03-25 17:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universeapp', '0003_our_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_service',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
