# Generated by Django 3.2 on 2022-03-25 17:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universeapp', '0004_alter_our_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
